[build]
  command = "cd react-app && npm install && npm run build"
  publish = "public/"[build]
  publish = "public/"
  command = "php bin/console cache:clear && php bin/console assets:install public && php bin/console assetic:dump"

[context.production.environment]
  APP_ENV = "prod"
